### PR TITLE
pcem: Use wxGtk3 instead, no longer need gtk2

### PR DESCRIPTION
**Pull request by WUGqnwvMQPzl**

### CODE REVIEW

**Comment by heavysink** [comment]
Switched to wxgtk3. I think this can be closed.

**Comment by WUGqnwvMQPzl** [comment]
刚刚重新检查了下，发现相关修改被 lilac 自动覆盖掉了：https://github.com/archlinuxcn/repo/commit/dec7bcea0cbb9f496d037d75a774f7c8121ac02f#diff-78048fe9a8ccc95b778a05c27fcece9d2333fa11a492599130d0e2d1147f5477

**Comment by hubutui** [comment]
@WUGqnwvMQPzl 这个包跟随 AUR，要改就去 AUR 提．

**Comment by heavysink** [comment]
忘了这包这是跟AUR的了，写了个lilac.py自动替换
https://github.com/archlinuxcn/repo/commit/e4303e076cc7bfc87bde675ec714766793095a1d

**Pull request closed without merging**
