### PR TITLE
Update PKGBUILD

### PR DESCRIPTION
**Pull request by taotieren**

### CODE REVIEW

**Comment by taotieren** [comment]
改成 `Debug` 编译出问题，便于调试分析。

**Comment by oldherl** [comment]
building with DEBUG might impact its performance

**Comment by MarvelousBlack** [comment]
RelWithDebInfo will include debugging symbols.
> We recommend using the RelWithDebInfo build type for personal release builds, as this will include debugging symbols that will give you more useful stack traces in case you encounter a crash. [1]

We  using devtools to package,  strip is enabled by default in `makepkg-x86_64.conf`.

> OPTIONS=(strip docs !libtool !staticlibs emptydirs zipman purge !debug)
>STRIP_BINARIES="--strip-all"
> STRIP_SHARED="--strip-unneeded"
> STRIP_STATIC="--strip-debug"

All symbols will be stripped, so now PKGBUILD using  CMAKE_BUILD_TYPE=RelWithDebInfo is useless.

I think use release is better.

If you need debug package you can build it by yourself, shipping debug package is not a good idea.
---
[1] https://dev-docs.kicad.org/en/build/linux/

**Comment by lilydjwg** [comment]
Use `options=('debug' 'strip')` to get a debug package alongside the normal one.

**Comment by taotieren** [comment]
> KiCad 使用 Ninja 编译系统代替 make 编译速度更快。要使用 Ninja ，可以在 CMake 命令行中指定 Ninja 输出：
> ```bash
> cmake -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo ../../
> ninja
> sudo ninja install
> ```

**Comment by taotieren** [comment]
我这边将 make 编译改成 Ninja 编译
编译速度时间将近减少了一倍
```bash
https://github.com/taotieren/arch_aur/actions
```

make 编译
image

Ninja 编译
image

**Comment by MarvelousBlack** [comment]
https://github.com/archlinuxcn/repo/commit/a109931a69763e3e6892492be4862a8c66a8f327

**Comment by taotieren** [comment]
> [a109931](https://github.com/archlinuxcn/repo/commit/a109931a69763e3e6892492be4862a8c66a8f327)

这样会和 kicad 环境冲突，我这边补充了下。https://github.com/archlinuxcn/repo/pull/2165

**Comment by taotieren** [comment]
> Use `options=('debug' 'strip')` to get a debug package alongside the normal one.

看着 lily 姐的回复，这次加上 `options=('debug' 'strip')`
https://github.com/archlinuxcn/repo/pull/2165

**Comment by taotieren** [comment]
> > [a109931](https://github.com/archlinuxcn/repo/commit/a109931a69763e3e6892492be4862a8c66a8f327)
> 
> 这样会和 kicad 环境冲突，我这边补充了下。#2165

之前 kicad 和 kicad-git 和 kicad-test 混用导致 kicad 和 kicad-git 环境出错。运行的时候会导致低版本的 kicad 组件会闪退报错。

**Comment by MarvelousBlack** [comment]
> kicad 和 kicad-git 和 kicad-test 混用

Don't do that.  
kicad and kicad-git are in conflict. How did you install them in same time?

**Comment by taotieren** [comment]
用户目录下的 ./config/kicad/ 里面的配置文件不会被替换。如果先 安装 kicad 再安装 kicad-git ，kicad-git 会保留以前的久的配置文件，然后再安装 kicad 并运行会用 kicad-git 的配置，这样来回测试会出现一些奇奇怪怪的问题。2021年4月2日 12:16，Megumi_fox ***@***.***>写道：



kicad 和 kicad-git 和 kicad-test 混用



Don't do that.

kicad and kicad-git are in conflict. How did you install them in same time?

**Pull request closed without merging**
