### PR TITLE
llvm-git: fix 2to3 thanks to new information that the python script is python3 compatible

### PR DESCRIPTION
**Pull request by SolarAquarion**

### CODE REVIEW

**Comment by yan12125** [comment]
GitHub says:

> **This branch cannot be rebased safely**
> Rebasing the commits of this branch on top of the base branch cannot be performed automatically as this would create a different result than a regular merge. 

Could you rebase locally and force-push?

**Comment by SolarAquarion** [comment]
Oh, ah, I'll do that

**Comment by yan12125** [comment]
Apparently git merge does not work in this case - GitHub complains the same. Most likely the issue is in the first commit (remove ocaml and python2), which is already merged in https://github.com/archlinuxcn/repo/pull/2925. Could you drop that commit?

**Comment by SolarAquarion** [comment]
I'll do that

**Pull request closed without merging**
