### PR TITLE
[balena-etcher]: build with system components instead of nvm

### PR DESCRIPTION
**Pull request by sukanka**
This pr builds balena-etcher with system nodejs and electron instead of using nvm. It also switch the sources from git to tar ball.

### CODE REVIEW

**Comment by zjuyk** [comment]
Great, wait for your issue https://github.com/balena-io/etcher/issues/4087

**Comment by zhullyb** [comment]
LGTM

**Comment by zhullyb** [comment]
How's it going now?

**Comment by sukanka** [comment]
I cannot build and run new etcher normally since the upstream changes its packaging method. I decide to close this now.

**Pull request closed without merging**
