### PR TITLE
python-fontmake: add package

### PR DESCRIPTION
**Pull request by auxiliarypower**

### CODE REVIEW

**Comment by lilydjwg** [comment]
不要给你的每个提交创建个 pr，除了 spam 大家的邮箱外没有意义。

**Comment by auxiliarypower** [comment]
> 不要给你的每个提交创建个 pr，除了 spam 大家的邮箱外没有意义。

I’m sorry for creating a pull request for each of my commits. I didn’t realize that it would spam everyone’s inbox. I will try to create pull requests only when my commits need your review.

**Comment by lilydjwg** [comment]
哦对了，还有个事：你既没有公开 github 邮箱，也没有在 lilac.yaml 里配置邮箱，lilac 没法向你发送错误报告。

**Comment by oldherl** [comment]
> > 哦对了，还有个事：你既没有公开 github 邮箱，也没有在 lilac.yaml 里配置邮箱，lilac 没法向你发送错误报告。
> 
> Thank you for your reminder. You suggested two ways to receive error reports from lilac, but both of them require me to expose my email address publicly. I prefer to keep my personal email private, is there any other solution that can allow me to receive error reports without revealing my email address to the public?

You can you an email forwarding service if you like.

**Comment by lilydjwg** [comment]
You can get an address dedicated for lilac and drop mails from any other addresses. You can even use your *username*@build.archlinuxcn.org address and create a [`.forward`](https://man.archlinux.org/man/forward.5) file to forward mails elsewhere.

**Pull request merged**
