### PR TITLE
electron25-bin: Add package

### PR DESCRIPTION
**Pull request by Kiri2002**
tested in extra-x86-64_build, namcap shown:
```
PKGBUILD (electron25-bin) W: Reference to x86_64 should be changed to $CARCH
PKGBUILD (electron25-bin) W: Reference to x86_64 should be changed to $CARCH
electron25-bin W: ELF file ('usr/lib/electron25/chrome-sandbox') lacks GNU_PROPERTY_X86_FEATURE_1_SHSTK.
electron25-bin W: ELF file ('usr/lib/electron25/chrome_crashpad_handler') lacks GNU_PROPERTY_X86_FEATURE_1_SHSTK.
electron25-bin W: ELF file ('usr/lib/electron25/chromedriver') lacks GNU_PROPERTY_X86_FEATURE_1_SHSTK.
electron25-bin W: ELF file ('usr/lib/electron25/electron') lacks GNU_PROPERTY_X86_FEATURE_1_SHSTK.
electron25-bin W: ELF file ('usr/lib/electron25/libEGL.so') lacks GNU_PROPERTY_X86_FEATURE_1_SHSTK.
electron25-bin W: ELF file ('usr/lib/electron25/libGLESv2.so') lacks GNU_PROPERTY_X86_FEATURE_1_SHSTK.
electron25-bin W: ELF file ('usr/lib/electron25/libffmpeg.so') lacks GNU_PROPERTY_X86_FEATURE_1_SHSTK.
electron25-bin W: ELF file ('usr/lib/electron25/libvk_swiftshader.so') lacks GNU_PROPERTY_X86_FEATURE_1_SHSTK.
electron25-bin W: ELF file ('usr/lib/electron25/libvulkan.so.1') lacks GNU_PROPERTY_X86_FEATURE_1_SHSTK.
electron25-bin E: custom is not a valid SPDX license identifier. See https://spdx.org/licenses/ for valid identifiers, or prefix the identifier with 'LicenseRef-', if it is custom.
electron25-bin W: File (usr/lib/electron25/chrome-sandbox) is setuid or setgid.
electron25-bin W: Unused shared library '/usr/lib/libpthread.so.0' by file ('usr/lib/electron25/chrome-sandbox')
electron25-bin W: Unused shared library '/usr/lib/libdl.so.2' by file ('usr/lib/electron25/chrome_crashpad_handler')
electron25-bin W: Unused shared library '/usr/lib/libpthread.so.0' by file ('usr/lib/electron25/chrome_crashpad_handler')
electron25-bin W: Unused shared library '/usr/lib/libdl.so.2' by file ('usr/lib/electron25/chromedriver')
electron25-bin W: Unused shared library '/usr/lib/libpthread.so.0' by file ('usr/lib/electron25/chromedriver')
electron25-bin W: Unused shared library '/usr/lib/libdl.so.2' by file ('usr/lib/electron25/electron')
electron25-bin W: Unused shared library '/usr/lib/libpthread.so.0' by file ('usr/lib/electron25/electron')
electron25-bin W: Unused shared library '/usr/lib/libdl.so.2' by file ('usr/lib/electron25/libEGL.so')
electron25-bin W: Unused shared library '/usr/lib/libpthread.so.0' by file ('usr/lib/electron25/libEGL.so')
electron25-bin W: Unused shared library '/usr/lib/libdl.so.2' by file ('usr/lib/electron25/libGLESv2.so')
electron25-bin W: Unused shared library '/usr/lib/libpthread.so.0' by file ('usr/lib/electron25/libGLESv2.so')
electron25-bin W: Unused shared library '/usr/lib/libpthread.so.0' by file ('usr/lib/electron25/libffmpeg.so')
electron25-bin W: Unused shared library '/usr/lib/libdl.so.2' by file ('usr/lib/electron25/libvk_swiftshader.so')
electron25-bin W: Unused shared library '/usr/lib/libpthread.so.0' by file ('usr/lib/electron25/libvk_swiftshader.so')
electron25-bin W: Unused shared library '/usr/lib/libdl.so.2' by file ('usr/lib/electron25/libvulkan.so.1')
electron25-bin W: Unused shared library '/usr/lib/libpthread.so.0' by file ('usr/lib/electron25/libvulkan.so.1')
electron25-bin-debug W: Directory (usr/src/debug/electron25-bin) is empty
```

### CODE REVIEW

**Comment by Kiri2002** [comment]
needed by lx-music (#3722 ) and [balena-etcher](https://github.com/archlinuxcn/repo/issues/3718)

**Comment by oldherl** [comment]
any reason to not use electron25 (build from source)?

**Comment by Kiri2002** [comment]
> any reason to not use electron25 (build from source)?

well, it qute hard to buid in my PC, 8G ram almost to die.

**Comment by Kiri2002** [comment]
I tested electron(source) from AUR, building in ArchCN's machine, it takes almost 1.5 hour to download and clone stuffs,
And then got error, totally talk almost 2 hour.
I thinks maybe use the -bin is good choice😭😭😭

**Pull request merged**
