### PR TITLE
改正openmsx的错误，把xnp2-svn换成xnp2，加入一些模拟器包等

### PR DESCRIPTION
**Pull request by heavysink**
openmsx原来忘记加python2的make dependency了。另外加入一些dependencies把它改成完全体。
xnp2-svn老是编译不成功，换成xnp2了
加了pcsx2-git pcsxr-git osdlyrics-git还有deadbeef-mpris2-plugin（deadbeef用的osdlyrics链接插件）
顺手把issue里面package request v2ray弄好了。

除了openmsx-catapult-git需要依赖openmsx-git以外，其他包均过相应devtools build(再有问题我拿块豆腐撞死算了）。

### CODE REVIEW

**Comment by heavysink** [comment]
错误是webkitgtk2，不是我的。

**Comment by colinkeenan** [comment]
What issue is webkitgtk2 causing? I just added it today.

**Comment by heavysink** [comment]
@colinkeenan TravisCI is complaining about webkitgtk2 error...

`FAIL: test_sections (__main__.ConfigSectionTest) (section='webkitgtk2')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./pre-commit", line 47, in test_sections
    '"\033[1;31m{0}\033[m" package').format(section))
AssertionError: False is not true : nvchecker.ini contains "webkitgtk2" section but there is no "webkitgtk2" package`

I think you added the package but somehow it is not recongized?

**Comment by colinkeenan** [comment]
I don't know anything about TravisCI. I know that the reason Arch dropped `gnucash` was that it depended on `webkitgtk2`. I added `webkitgtk2` just so to make it easy to build future versions of `gnucash`.

Should `webkitgtk2` be dropped while still keeping `gnucash`? 

What does the TravisCI gnucash error mean anyway?

**Comment by lilydjwg** [comment]
@colinkeenan you've added a split package which pkgbase is webkitgtk, but in nvchecker.ini you've written webkitgtk2. That's the error.

**Comment by colinkeenan** [comment]
Ok. I wondered how to handle that. So, I will just remove the `2` at the end.

**Comment by colinkeenan** [comment]
I have removed the 2 so `nvchecker.ini` just has `webkitgtk` now.

**Comment by lilydjwg** [comment]
@heavysink  I hope these will build fine. I'll take a look into your application soon.

**Pull request merged**
