### PR TITLE
android-sdk-build-tools: fix wrong target path

### PR DESCRIPTION
**Pull request by NextAlone**

### CODE REVIEW

**Comment by yan12125** [comment]
Thanks for catching and fixing it. This package follows the one on AUR. Could you send the fix to https://aur.archlinux.org/packages/android-sdk-build-tools instead?

**Comment by NextAlone** [comment]
> Thanks for catching and fixing it. This package follows the one on AUR. Could you send the fix to https://aur.archlinux.org/packages/android-sdk-build-tools instead?

ok

**Comment by NextAlone** [comment]
Just sync this changes, request has been pushed to AUR.

**Comment by yan12125** [comment]
Thanks! When the fix is merged on AUR, the package will be updated as well.

**Comment by yan12125** [comment]
Upstream took a different approach to fix the issue [1][2]. Closing as the issue is fixed, anyway.

[1] https://github.com/archlinuxcn/repo/commit/2f2b784835bcab24dc42acf8afe46220f13e476d
[2] https://aur.archlinux.org/cgit/aur.git/commit/?h=android-sdk-build-tools&id=3f5498d45ae4d0287ee2fd18382b701fa1e479a4

**Pull request closed without merging**
