### PR TITLE
firefox-kde-opensuse: sync with aur

### LINKED ISSUE #2452: please update firefox-kde-opensuse
### 问题类型 / Type of issues

* 过期软件包 / out-of-date packages

### 受影响的软件包 / Affected packages

* firefox-kde-opensuse
----

### PR DESCRIPTION
**Pull request by pickfire**
Fix #2452

### CODE REVIEW

**Comment by pickfire** [comment]
```
Run ./pre-commit --all
======================================================================
FAIL: test_repo_depends_valid (__main__.RepoTreeTest) (package='cloog')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./pre-commit", line 418, in test_repo_depends_valid
    self.assertTrue(
AssertionError: False is not true : package "cloog" depends on "osl", which does not exist or is unmanaged
```
这有关系吗？

**Comment by lilydjwg** [comment]
没关系。

**Comment by farseerfc** [comment]
sorry, I am dropping this in #2612 . We need another maintainer for this if firefox-appmenu is not enough.

**Comment by oldherl** [comment]
Closing as the package is dropped.

**Pull request closed without merging**
