### PR TITLE
New package: rak - Grep replacement in pure Ruby

### PR DESCRIPTION
**Pull request by farkasity**

### CODE REVIEW

**Comment by lilydjwg** [comment]
You need to provide a `lilac.py` when you open PRs, or there won't be any package in the repository even merged.

However I've seen your application mail. I'll process it soon.

**Comment by farkasity** [comment]
I have added missing lilac.py, but I thought it maybe inconvenient, maybe we could trying to simplify it by reflect lilac.

**Comment by lilydjwg** [comment]
Go ahead and send PRs to [lilac](https://github.com/archlinuxcn/lilac) then :-)

PS: using `aur_post_build` might cause problems; there are (or were) other gem packages in the repo and you can take a look at them.

**Comment by farkasity** [comment]
OK. I will optimize lilac.py latterly.

**Pull request merged**
