### PR TITLE
qv2ray-dev-git: delete lilac.py

### PR DESCRIPTION
**Pull request by DuckSoft**
removed since we should not update AUR if it's a VCS package

### CODE REVIEW

**Comment by yuyichao** [comment]
Doesn't this affect update of manual update as well?

**Comment by yuyichao** [comment]
And I believe liliac is no longer pushing any commit that is violating the AUR convention anymore.

**Comment by lilydjwg** [comment]
It's OK to use `update_aur_repo` for vcs packages now, because it will no longer push useless commits.

**Comment by yuyichao** [comment]
Also ref https://github.com/archlinuxcn/repo/pull/1658#discussion_r436277351 which I think should also be kept unless the PKGBUILD will never be editted manually or if the AUR should not be kept in sync.

**Comment by DuckSoft** [comment]
Okay. Closing this.

**Pull request closed without merging**
