### PR TITLE
fix the PKGBUILD of lilac-git

### PR DESCRIPTION
**Pull request by starsareintherose**

### CODE REVIEW

**Comment by starsareintherose** [comment]
@lilydjwg

**Comment by yan12125** [comment]
Thanks for keeping this package fresh and sorry for messing up the package on AUR. I'm not sure if syncing from this repo to AUR via update_aur_repo() is really a good idea. How about syncing from AUR to this repo via aur_pre_build/aur_post_build instead?

**Comment by starsareintherose** [comment]
That's fine

**Comment by lilydjwg** [comment]
python-sqlalchemy is now optional.

**Comment by starsareintherose** [comment]
okay

**Comment by yan12125** [comment]
Thanks for the update! Could you also add an entry to `update_on` to trigger updates in this repo when PKGBUILD on AUR is updated?

> python-sqlalchemy: sql

May be better as: `python-sqlalchemy: for recording build results in a database`

**Comment by starsareintherose** [comment]
I've updated

**Comment by yan12125** [comment]
Ah, forgot to mention, old `pre_build_script` and `post_build_script` blocks should be removed.

**Comment by oldherl** [comment]
> Thanks for keeping this package fresh and sorry for messing up the package on AUR. I'm not sure if syncing from this repo to AUR via update_aur_repo() is really a good idea. How about syncing from AUR to this repo via aur_pre_build/aur_post_build instead?

I thought syncing from archlinuxcn to AUR was preferred over the other way around.

**Comment by starsareintherose** [comment]
> Ah, forgot to mention, old `pre_build_script` and `post_build_script` blocks should be removed.

deleted

**Comment by starsareintherose** [comment]
> > Thanks for keeping this package fresh and sorry for messing up the package on AUR. I'm not sure if syncing from this repo to AUR via update_aur_repo() is really a good idea. How about syncing from AUR to this repo via aur_pre_build/aur_post_build instead?
> 
> I thought syncing from archlinuxcn to AUR was preferred over the other way around.

both are okay, I am the maintainer of lilac-git in AUR, usually, I hope it can be auto-updated, I am lazy enough, so don't worry about this

**Comment by yan12125** [comment]
> I thought syncing from archlinuxcn to AUR was preferred over the other way around.

Well, that depends case-by-case. For this package, syncing from [archlinuxcn] to AUR means that to update this package, @starsareintherose needs to submit a pull request, waiting for a few days for reviews and the lilac schedule. Such a delay can be avoided. I will merge this to unbreak the package for now. If there are better suggestions, feel free to propose!

**Pull request merged**
