### PR TITLE
Multiple fixes on ZeroNet

### LINKED ISSUE #1462: zeronet wants Python 3
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* zeronet

----

```
env[341453]: Error: Python 3.x is required
```

### PR DESCRIPTION
**Pull request by outloudvi**
Fix #1462

Also please refer to HelloZeronet/ZeroNet#2375.

### CODE REVIEW

**Comment by imlonghao** [comment]
Human build bot: **Failed** ([Full log](https://p.esd.cc/v83NBe))

```
==> Starting package()...
cp: cannot stat '/build/zeronet/src/ZeroNet-0.7.1/.': No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
```

**Comment by outloudvi** [comment]
Shall be working now.

**Comment by outloudvi** [comment]
The fix seems a little weird... I got

```
- UiWSGIHandler error: AttributeError: module 'cgi' has no attribute 'parse_qsl' in UiServer.py line 41 > pywsgi.py line 923 > UiServer.py line 98
```

when attempting to visit the WebUI (http://127.1:43110/).

**Comment by yan12125** [comment]
Looks like ZeroNet is fixed in a separate commit? https://github.com/archlinuxcn/repo/commit/ee755bf30bf5dc076780a2cbed851caf34a2b03a

**Comment by outloudvi** [comment]
@yan12125 That's the fix I said in the last comment to be "a little weird" and unable to show the WebUI.

**Comment by yan12125** [comment]
Outvi V <notifications@github.com> 於 2020年4月13日 週一 下午4:19寫道：
>
> @yan12125 That's the fix I said in the last comment to be "a little weird" and unable to show the WebUI.
>

Oops I misunderstood your previous comments.

Looks like the fix is in upstream master
(https://github.com/HelloZeroNet/ZeroNet/commit/456e330854acdfbf706c601b7dcdc49501ac58ae)
but not released yet.

**Comment by outloudvi** [comment]
Seems the the current `PKGBUILD` is working with current HEAD HelloZeroNet/ZeroNet@f3a839f422afd50f5bf8f17d83a8807571bc1dfe (although new dependencies may apply). Closing this PR.

**Pull request closed without merging**
