### PR TITLE
addpkg: yass-proxy-cli, yass-proxy-gtk3, yass-proxy-qt5, yass-proxy-qt6

### PR DESCRIPTION
**Pull request by Chilledheart**
below packages are affected:

- yass-proxy-cli: CLI variant of yass-proxy

- yass-proxy: GTK4 variant of yass-proxy
- yass-proxy-gtk3: GTK3 variant of yass-proxy
- yass-proxy-qt5: QT5 variant of yass-proxy
- yass-proxy-qt6: QT6 variant of yass-proxy

### CODE REVIEW

**Comment by rocka** [comment]
You need to add PKGBUILD files to the repo in order to actually build the package.

**Comment by Chilledheart** [comment]
> You need to add PKGBUILD files to the repo in order to actually build the package.

PKGBUILDs have been in aur repo already and will be synced by lilac after merge:
- https://aur.archlinux.org/packages/yass-proxy-cli
- https://aur.archlinux.org/packages/yass-proxy-qt5
- https://aur.archlinux.org/packages/yass-proxy-qt6
- https://aur.archlinux.org/packages/yass-proxy-gtk3

**Comment by Chilledheart** [comment]
截屏2024-07-20 21 07 28

**Comment by lilydjwg** [comment]
I don't understand why `go build` is run in `prepare()`.

**Comment by Chilledheart** [comment]
> I don't understand why `go build` is run in `prepare()`.

Thanks for taking care of the details of PKGBUILD files. Nice catch!

It is not golang program but cmake project (C++ program). And the "go build" is used to build the wrapper tool to call cmake but the built tool under tool directory is no longer used for PKGBUILDs because cmake is invoked directly in `build()` stage.

Actually, the tool with "go build" is kind of build script (originally written in python and replaced by golang) and used for yass's gtk3 binary only such as this Github Actions https://github.com/Chilledheart/yass/actions/workflows/releases-linux-binary.yml. Somehow, I forgot to remove these calls somehow after the initial change of aur repo's PKGBUILD files. These calls will be removed.

**Comment by Chilledheart** [comment]
> In short, these calls (including the whole `prepare()` stage) will be removed.

The unused code has been removed.

**Comment by Chilledheart** [comment]
errno=ETIMEDOUT

**Pull request closed without merging**
