### PR TITLE
rust-nightly: add optdepend for rust-analyzer-nightly

### PR DESCRIPTION
**Pull request by Y7n05h**

### CODE REVIEW

**Comment by lilydjwg** [comment]
I prefer it to be `optdepends`, because the user may already have the source elsewhere (e.g. they pull the rustc git repo locally).

**Comment by Y7n05h** [comment]
You are right. But `rust-src` is a dependency of `community/rust-analyzer`, do we need to be consistent with `community/rust-analyzer` ?

**Comment by lilydjwg** [comment]
No. Being different than Arch's official packages is one of the repository's use cases.

**Comment by Y7n05h** [comment]
OK, I have fixed it.

**Pull request merged**
