### PR TITLE
Bump meli git version

### PR DESCRIPTION
**Pull request by pickfire**

### CODE REVIEW

**Comment by imlonghao** [comment]
Package build failed, PKGBUILD need update instead.

```
error: failed to run custom build command for `libdbus-sys v0.2.1`

Caused by:
  process didn't exit successfully: `/build/meli-git/src/meli/target/release/build/libdbus-sys-d157ea395f7f8433/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failure { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"dbus-1\" \"dbus-1 >= 1.6\"", output: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "Package dbus-1 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `dbus-1.pc\'\nto the PKG_CONFIG_PATH environment variable\nPackage \'dbus-1\', required by \'virtual:world\', not found\nPackage \'dbus-1\', required by \'virtual:world\', not found\n" } }', /build/.cargo/registry/src/github.com-1ecc6299db9ec823/libdbus-sys-0.2.1/build.rs:6:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

warning: build failed, waiting for other jobs to finish...
error: build failed
make: *** [Makefile:48: meli] Error 101
```

**Comment by pickfire** [comment]
@imlonghao How do we know if the build pass or failed? Is there like a CI?

**Comment by DuckSoft** [comment]
Good question. Maybe I can setup a GitHub Actions for a reference.

**Comment by farseerfc** [comment]
I think meli-git cannot build due to a different problem. I commit a fix to the repo and hope that will fix the build. Let's see for the next lilac build.

**Pull request merged**
