### PR TITLE
Add mark-mind-git

### PR DESCRIPTION
**Pull request by taotieren**

### CODE REVIEW

**Comment by yan12125** [comment]
```Diff
+ maintainers:
+   - github: taotieren
+ 
```

As an email is not listed in `lilac.yaml`, lilac will use the email registered for your GitHub account. In this case, it is admin@taotieren.com as seen on https://github.com/taotieren. However, taotieren.com seems gone. Could you fix your domain or swtich to another email address?

**Comment by taotieren** [comment]
> ```diff
> + maintainers:
> +   - github: taotieren
> + 
> ```
> 
> As an email is not listed in `lilac.yaml`, lilac will use the email registered for your GitHub account. In this case, it is [admin@taotieren.com](mailto:admin@taotieren.com) as seen on https://github.com/taotieren. However, taotieren.com seems gone. Could you fix your domain or swtich to another email address?

Thanks!

**Comment by yan12125** [comment]
Hmm, seems I was not clear enough.

I wanted to say that the domain name `taotieren.com` cannot be resolved:

```
$ drill MX taotieren.com @8.8.8.8
;; ->>HEADER<<- opcode: QUERY, rcode: SERVFAIL, id: 18560
;; flags: qr rd ra ; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0 
;; QUESTION SECTION:
;; taotieren.com.       IN      MX

;; ANSWER SECTION:

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 180 msec
;; SERVER: 8.8.8.8
;; WHEN: Wed Jul 21 23:40:23 2021
;; MSG SIZE  rcvd: 31
```

so that lilac mails cannot reach admin@taotieren.com, while a working email is a requirement for package maintainers for this repo.

I just checked further and found that DNSSEC settings are wrong for `taotieren.com`. As depicted on https://dnsviz.net/d/taotieren.com/dnssec/, there are no necessary DNSKEY records.

圖片

**Comment by taotieren** [comment]
image

**Comment by yan12125** [comment]
Hmm, I wonder if some configuration disables DNSSEC for drill on your machine. Assume you are not under DNS pollution, setting the Authentic Data (AD) bit and unsetting the Checking Disabled (CD) bit will force DNSSEC validation. For example,
```
archlinuxcn-build-e5% drill -o AD,cd -V5 MX taotieren.com @8.8.8.8  
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 0
;; flags: rd ad ; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0 
;; QUESTION SECTION:
;; taotieren.com.       IN      MX

;; ANSWER SECTION:

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 0 msec
;; WHEN: Thu Jul 22 18:05:34 2021
;; MSG SIZE  rcvd: 0
;; ->>HEADER<<- opcode: QUERY, rcode: SERVFAIL, id: 32284
;; flags: qr rd ra ; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0 
;; QUESTION SECTION:
;; taotieren.com.       IN      MX

;; ANSWER SECTION:

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 391 msec
;; SERVER: 8.8.8.8
;; WHEN: Thu Jul 22 18:05:34 2021
;; MSG SIZE  rcvd: 31
```
This time I run the command on archlinuxcn's build server (build.archlinuxcn.org) to make sure it's not only an issue on my machine.

> I am using Aliyun's mailbox, which can receive mail from other regions.

Yeah, DNSSEC is often misconfigured, so many clients just ignore it...

**Comment by lilydjwg** [comment]
Google, Cloudflare, OpenDNS, TWNIC, TUNA and IBM returns SERVFAIL for your domain, and Cloudflare even says the reason:

```
>>> dig taotieren.com MX

; <<>> DiG 9.16.18 <<>> taotieren.com MX
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 58188
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; EDE: 6 (DNSSEC Bogus)
;; QUESTION SECTION:
;taotieren.com.                 IN      MX

;; Query time: 3 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Thu Jul 22 18:18:42 CST 2021
;; MSG SIZE  rcvd: 48
```

There are some DNS servers that can return results (e.g. 114, Level3, HiNet, ChinaUnicom, CNNIC, Baidu, DNSPod). But that's not a reason to switch to a poorer DNS service.

**Comment by taotieren** [comment]
I set the DNS resolution to overseas, and now I see if I can access it normally.2021年7月22日 18:25，依云 ***@***.***>写道：
Google, Cloudflare, OpenDNS, TWNIC, TUNA and IBM returns SERVFAIL for your domain, and Cloudflare even says the reason:
>>> dig taotieren.com MX

; <<>> DiG 9.16.18 <<>> taotieren.com MX
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 58188
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; EDE: 6 (DNSSEC Bogus)
;; QUESTION SECTION:
;taotieren.com.                 IN      MX

;; Query time: 3 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Thu Jul 22 18:18:42 CST 2021
;; MSG SIZE  rcvd: 48

There are some DNS servers that can return results (e.g. 114, Level3, HiNet, ChinaUnicom, CNNIC, Baidu, DNSPod). But that's not a reason to switch to a poorer DNS service.

**Comment by imlonghao** [comment]
这和你的域名海外解析都没有关系，你应该去检查你的域名 DNSSEC 配置是否正确（在设置域名 MX 记录、处理域名续费的那个地方）
另外你可以去这里看你的域名全球大部分解析都是 SERVFAIL 的 https://ping.sx/dig?t=taotieren.com

**Comment by taotieren** [comment]
> 这和你的域名海外解析都没有关系，你应该去检查你的域名 DNSSEC 配置是否正确（在设置域名 MX 记录、处理域名续费的那个地方）
> 另外你可以去这里看你的域名全球大部分解析都是 SERVFAIL 的 https://ping.sx/dig?t=taotieren.com

重新配置后大部分地区解析 `NOERROR`

**Comment by lilydjwg** [comment]
是 NOERROR 了，但是没结果啊……现在 NS 有 hichina 和 cloudflare 两家，但是 cloudflare 那边不管是 A 还是 MX 都是没结果……

**Comment by yan12125** [comment]
算了，還是來聊聊包本身的問題吧
```
$ offload-build 
==> 製作軟體包中：mark-mind-git 1.1.9.0.8.g7ee8071-1 (西元2021年07月24日 (週六) 17時24分46秒)
==> 擷取來源中...
==> 錯誤： 無法在 build 目錄找到 mark-mind.desktop ，且非合法的網址。
error: unable to make source package
```

**Comment by taotieren** [comment]
> ```diff
> + maintainers:
> +   - github: taotieren
> + 
> ```
> 
> As an email is not listed in `lilac.yaml`, lilac will use the email registered for your GitHub account. In this case, it is [admin@taotieren.com](mailto:admin@taotieren.com) as seen on https://github.com/taotieren. However, taotieren.com seems gone. Could you fix your domain or swtich to another email address?

GitHub 的主邮箱已更新，再次验证一下是否可以合并。

**Comment by yan12125** [comment]
需要再上傳 mark-mind.desktop

**Comment by taotieren** [comment]
> 需要再上傳 mark-mind.desktop

已更新

**Comment by yan12125** [comment]
Building now fails with another error:
```
==> Starting check()...

> mind@1.1.9 test
> node ./test/test_mind_node.spec.js

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '/build/mark-mind-git/src/mark-mind-git/test/test_mind_node.spec.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v17.3.0
```

**Comment by taotieren** [comment]
上游仓库停更，关闭此 PR

**Pull request closed without merging**
