### PR TITLE
fix(cleanup): remove pkgs that already in official repo

### LINKED ISSUE #2740: python-cli_helpers in official repos now
### 问题类型 / Type of issues

* 软件包被官方仓库收录 / available in official repos

### 受影响的软件包 / Affect packages

* python-cli_helpers

### PR DESCRIPTION
**Pull request by masakichi**
close #2740 #2741

Hey @Sasasu , I'm not sure if it needs a manual operation, I create this PR to remove pkgs/dependencies that are already in the official repository. lgtu?

### CODE REVIEW

**Comment by yan12125** [comment]
FWIW, issues with `in-official-repos` will be closed and corresponding packages will be removed by lilac after 4 days (if there are no other activities on those issues)

**Comment by masakichi** [comment]
Hey @yan12125 
Thanks for your explanation, what I'm not sure is that if it will also update packages' lilac.yaml with `repo_depends` defined.

**Comment by yan12125** [comment]
> if it will also update packages' lilac.yaml with repo_depends defined.

Yep! Here is an example: https://github.com/archlinuxcn/repo/commit/6e47ea4c54f03f904e317b913c34e3bc3ccc49ab. An issue is that lilac removes comments and blank lines in `lilac.yaml` files. It you don't want that, a manual update like this PR is good.

**Comment by masakichi** [comment]
Cool, that's good to know!👍

I'll merge this PR for this time, next time will just let lilac do it in silence.

**Pull request merged**
