### PR TITLE
webkitgtk: update from AUR; fixed building with enchant 2.x

### PR DESCRIPTION
**Pull request by yan12125**
This is basically the same as https://aur.archlinux.org/cgit/aur.git/commit/?h=webkitgtk&id=42cc417a1edb3f36eef984a12f9f059f242ea19b except the ```epoch``` part.

cc @colinkeenan

### CODE REVIEW

**Comment by colinkeenan** [comment]
I have been building it for several hours now, but had forgotten that I added epoch=3 to it in the past. I guess I'll start over.

**Comment by lilydjwg** [comment]
@colinkeenan you can use the build machine, which will be much faster.

**Comment by colinkeenan** [comment]
I don't know how.

**Comment by lilydjwg** [comment]
@colinkeenan You still have your private key, right? `ssh colinkeenan@build.archlinuxcn.org`, then put your PKGBUILD etc somewhere, run `extra-x86_64-build` instead of `makepkg` to build.

**Comment by colinkeenan** [comment]
I will look at that next time.Now going to sleep while it's building. It will be done when I get up.

**Comment by colinkeenan** [comment]
I uploaded webkitgtk and webkitgtk2 twice. The first time, I accidentally uploaded a bad signature file that was made against both of them.

**Pull request closed without merging**
