### PR TITLE
oh-my-posh: support shell auto-completion

### PR DESCRIPTION
**Pull request by wszqkzqk**
Support shell auto-completion for oh-my-posh.

### CODE REVIEW

**Comment by auxiliarypower** [comment]
@wszqkzqk I have seen your [previous merge request](https://github.com/archlinuxcn/repo/pull/3007), and I understand that it would introduce unnecessary version number updates, but I wonder if it is inconvenient for you to manually submit requests every time the AUR updates.

**Comment by wszqkzqk** [comment]
> @wszqkzqk I have seen your [previous merge request](https://github.com/archlinuxcn/repo/pull/3007), and I understand that it would introduce unnecessary version number updates, but I wonder if it is inconvenient for you to manually submit requests every time the AUR updates.

No, it's automatically updated by lilac.

**Comment by auxiliarypower** [comment]
> No, it's automatically updated by lilac.

What I mean is, if lilac stops following the AUR updates, it can only automatically update the version number and hash value. If you have any other changes on the AUR, you will need to manually submit merge requests every time.

**Comment by wszqkzqk** [comment]
> > No, it's automatically updated by lilac.
> 
> What I mean is, if lilac stops following the AUR updates, it can only automatically update the version number and hash value. If you have any other changes on the AUR, you will need to manually submit merge requests every time.

But this change is not so frequent.

**Comment by auxiliarypower** [comment]
@Y7n05h It turns out that the file conflict was caused by lilac’s automatic update, so I’ll merge it first to avoid repeated conflicts. I apologize for the inconvenience I caused you by not letting you review it before merging.

**Comment by auxiliarypower** [comment]
@wszqkzqk The upstream updates frequently, so if it is not necessary to manually trigger lilac to rebuild, we can wait until the next lilac automatic update to support the autocomplete feature. If there is no problem, I’ll merge your request.

**Pull request merged**
