### PR TITLE
add riscv-none-embed

### PR DESCRIPTION
**Pull request by sequencer**
1. use official gnu upstream, rather than SiFive.
2. patch config.sub with embed in os.
3. disable libgloss default linking.

### CODE REVIEW

**Comment by sequencer** [comment]
Currently, riscv toolchain is using gcc with `libgloss` for both embed device and Linux, which is vended by SiFive, with the prefix `riscv64-unknown-elf`.
This cause too much trouble for embedded device usage, and [gnu-mcu-eclipse](https://github.com/gnu-mcu-eclipse/riscv-none-gcc) tried to fix the `libgloss` problem. This package takes the idea of gnu-mcu-eclipse to add `embed` to OS in `config.sub`, and remove the `libgloss` default linking.  
However, gnu-mcu-eclipse still stick on the [riscv-gcc](https://github.com/riscv/riscv-gcc/) branch, which didn't update for a long time. Since RISC-V has been upstreamed for since gcc7. This package patches the GNU upstream to provide the newest version of `riscv-none-embed`.

**Comment by Sasasu** [comment]
please add `lilac.py` and `lilac.yaml` for each package.  The auto build system uses those files to monitoring a package.

lilac.py is a historical problem, just put an empty file.

lilac.yaml describe when can this package update or rebuild.

yaml schema file for lilac.yaml: https://github.com/archlinuxcn/repo/blob/master/lilac-yaml-schema.yaml 
manually update example: https://github.com/archlinuxcn/repo/search?l=YAML&q=manual 
track aur example: https://github.com/archlinuxcn/repo/search?l=YAML&q=aur_pre_build

**Comment by ilg-ul** [comment]
> However, gnu-mcu-eclipse still stick on the riscv-gcc branch

this is not accurate, gnu-mcu-eclipse now follows the SiFive fork https://github.com/sifive/riscv-gcc.

> use official gnu upstream, rather than SiFive.

by doing this you miss the SiFive extensions (like interrupt attributes), and you cannot use your toolchain to build the SiFive Freedom SDK projects.

if you insist on doing this, I think you should explicitly mention this difference in the package metadata.

**Comment by sequencer** [comment]
OK, I’ll collect a set of patch from SiFive gcc and maintain a patch to upstream.

**Comment by ilg-ul** [comment]
I think this is a better approach.

Also keeping a consistent functionality with **GNU MCU Eclipse RISC-V Embedded GCC** (which will be soon renamed **xPack RISC-V Embedded GCC** and moved from **GNU MCU Eclipse** to a new **xPack Development Tools** project) would be prefered, toolchains with identical names but different functionality are confusing.

**Comment by sequencer** [comment]
I also give this [issue](https://github.com/riscv/riscv-gcc/issues/157).
How a about change this packages’ prefix to `riscv-none-gnu`?

**Comment by ilg-ul** [comment]
To my knowledge, GNU is an UNIX like operating system, not related with embedded/bare metal devices which `riscv-none-embed` addresses.

**Comment by sequencer** [comment]
OK I'll close this PR, after finishing the patch work, I will reopen it.

**Comment by sequencer** [comment]
@ilg-ul cherry picked unmerged commit from https://github.com/sifive/riscv-gcc.

**Comment by sequencer** [comment]
Ping

**Comment by ilg-ul** [comment]
Pong.

Sorry, but I cannot follow you, if you cherry pick individual commits, you are on your own, I don't know the details of SiFive development. In my release I used exactly the same sources as they said they did and compiled them as is. If I remember right, the only deviation was for GDB, which had some problems and I used a more recent commit.

**Comment by ilg-ul** [comment]
Did you manage to integrate the toolchain in your distribution?

**Comment by sequencer** [comment]
Currently I use `riscv64-linux-gnu-` as prefix with `-nostdinc` and `-nostdlib` for compiling. It's from the upstream.
Locally, I use upstream with local custom patch to create different packages for custom instruction integration.

**Pull request closed without merging**
