### PR TITLE
enable more supports for gtkwave

### PR DESCRIPTION
**Pull request by sequencer**

### CODE REVIEW

**Comment by SilverRainZ** [comment]
@DDoSolitary

**Comment by DDoSolitary** [comment]
Sorry I'm busy with exams recently. Will take a look this weekend.

**Review by DDoSolitary — CHANGES_REQUESTED** [review]
Please don't mix indentations. Either use tabs or replace all existing tabs with spaces.

**Comment by DDoSolitary** [comment]
Closing as no response to requested changes.

**Pull request closed without merging**
