### PR TITLE
Fixing lilac.yaml

### PR DESCRIPTION
**Pull request by SolarAquarion**
Because auracle on this repo seems to be outdated

### CODE REVIEW

**Comment by SolarAquarion** [comment]
@yan12125 @colinkeenan

**Comment by yan12125** [comment]
Is there a reason to tag me? I have never maintained this package. I have never used auracle, either.

**Comment by SolarAquarion** [comment]
Okay sure

**Comment by SolarAquarion** [comment]
@yuyichao i wonder if this can be merged.

**Comment by yan12125** [comment]
Anyway, using a periodic timer with `time.time()` seems inappropriate as the upstream repository is not updated very frequently. This approach is considered needed only for repositories that are updated many times a day and building for each update takes long time (e.g., more than an hour).

**Comment by SolarAquarion** [comment]
Gotcha, so just vcs for that

**Comment by SolarAquarion** [comment]
i just polluted the git history, lmao

**Comment by yan12125** [comment]
Please do proper rebase.

**Pull request closed without merging**
